### ISSUE TITLE
Upstream integration

### ISSUE THREAD

**Issue by fitojb** [shimmerproject/libreoffice-style-elementary#1]
Hi,

I’m so glad I found this project! I would like to have this work integrated into LibreOffice upstream, but first I would like to know if you are interested in working with us to replace LibreOffice’s “Human” theme with this. If so, I will be glad to help you with it. As a LibreOffice contributor, I would rather kill the unmaintained Human theme (which was never completed and contains many old-looking Industrial and Galaxy icons), and having it replaced with something more modern; currently (X)ubuntu suffers from this, as it uses the Human theme by default. With your permission, I think we can rename Human to elementary and push your icons to the LibreOffice repository.

Let me know if you’re interested. Thanks!

**Comment by ochosi** [comment]
Hey, thanks for your interest!
That sounds great – I'd be totally up for that!

One thing (of the many things) that is still WIP and which might be a small roadblock is the licensing stuff. We saw that Human lists icons individually and I haven't documented all of that yet. Partly because I'm not sure whether it's actually needed. If you could check that with upstream, that'd be great!

**Comment by fitojb** [comment]
The individual icon list [is not necessary](https://bugs.documentfoundation.org/show_bug.cgi?id=92458#c1) – other icon themes in LibreOffice don’t have one. Attribution is either indicated in the form of a note in a commit’s message or in a commit’s “author” field. :smile:

**Comment by ochosi** [comment]
Perfect! In this case I guess we can break down our current list to a few statements.

I'm planning to do a first 0.1 release soonish, there are only a few icons left for the standard toolbars of -writer and -calc. How would you like to proceed? Would you sync the icons to upstream release-wise or would you do snapshots too?

**Comment by fitojb** [comment]
I’m fine either way! I’d be inclined to do snapshots, but it depends on the speed of the releases I guess. Another way would be that one of you guys (or you all) [create an account in our Gerrit instance](https://wiki.documentfoundation.org/Development/gerrit/setup) to push the icons yourselves, but of course I can push for you using git’s `--author` option, in case you don’t want to clone the LibreOffice repo (it’s a quite large download, I know).

**Comment by ochosi** [comment]
Hmyeah, I guess snapshots are the best way to get things upstream. The git log will tell you what changed and whether a new snapshot makes sense. I'll try to do regular releases, but in my own experience with myself I'd say I'm not always forceful enough to pull it off ;)

Also in terms of review/testing I'd prefer if you could keep pushing things upstream as a sort of go-between. While icon-themes aren't critical, an extra set of eyes never hurts.

**Comment by knomepasi** [comment]
Just a brief note from a co-author (with notably less contributions though), I think this is a great direction generally.

I agree with everything Simon has said. Particularly; snapshots sound the sanest way to go forward, another review wouldn't hurt at all and finally, regular releases aren't to be expected.

All that said, (more or less) continuing communication both ways would be good to have (even requests for specific icons are welcome) - we might just be able to pull of some releases to match other upstream events when needed. You can join our IRC channel #shimmer (on Freenode) at any time to discuss matters further or talk about details.

**Comment by philipzae** [comment]
@ochosi: you mentioned that you have nearly completed the icons in the standard toolbars in writer and calc and just wanted to bring to your attention, encase you didnt already know, that the toolbars have changed in libreoffice 4.4 and the upcoming 5.0.

**Comment by ochosi** [comment]
@philipzae: Yes, I noticed that there are a few more new icons there. I'll get to those soonish (currently a bit busy with other things). As an example though, I'm not sure what a meaningful distinction between "insert footnote" and "insert endnote" would look like in 24px. Who knows, maybe I'll figure that one out too ;)

**Comment by philipzae** [comment]
@ochosi: Yes that tango icons dont show a good representation of the distinction between the two, but breeze and sifr do. Footnotes uses regular numbers and endnotes use roman numbers. Sifr uses a text based presentation of the distinction, while breeze uses an image based distinction that shows has multiple pages, as endnotes always appear at the end of a document.

Sifr ![sifr](https://cloud.githubusercontent.com/assets/4412114/8513345/65309bce-2378-11e5-9d0c-0a0778180b0e.png)

Breeze ![breeze](https://cloud.githubusercontent.com/assets/4412114/8513344/5d1aa7b8-2378-11e5-8847-a60a4d91f7ff.png)

**Comment by ochosi** [comment]
@fitojb: So I'm tempted to close this issue, but you can report on the progress of upstream integration here if you like, I'm definitely curious how it's going. (Currently a bit busy and afk, but hopefully back again soon.)

**Comment by fitojb** [comment]
@ochosi: Sure, feel free to close the issue in the meantime. I haven’t done nothing on the LibreOffice side yet, but I’ll keep you all informed. Thanks!

**Comment by philipzae** [comment]
Björn Michaelsen from canonical has moved the contents of libreoffice-style-elementary into the repo. It would be useful to know which icon theme was used as the fallback icon theme for missing icons from the icon theme, so we can set the same in the repo.

**Comment by philipzae** [comment]
Now that the icon theme has been integrated, the duplicate icons from human, industrial and galaxy should be removed from it. https://bugs.documentfoundation.org/show_bug.cgi?id=94878

I've created a google doc to track suggestions for improvements to icons.
https://docs.google.com/document/d/1rCawF_sTm_PJhGFwZ9PM0HTj6-BU7NGWLpqwmzOBAJ0/edit?usp=sharing

**Comment by ochosi** [comment]
I'm not entirely sure that dropping all duplicate/fallback icons is really a great idea, cause that would mean people would have to install both the human and the elementary theme to get the full experience (at least until elementary is complete - and nobody knows whether it will ever be).

**Comment by philipzae** [comment]
Libreoffice's icon theme system requires that fallback icon themes be installed when installing a theme that is incomplete and that is being implemented at the package maintainer level. https://lists.debian.org/debian-openoffice/2015/09/msg00343.html

Having multiple copies of the same icon in different icon themes makes it more work to keep track of changes. Tango falls back on industrial, so during the building process, it copies missing icons from industrial into the images_tango.zip, so in a similar fashion, missing icons from human should be copied into the images_elementary.zip during the building process.
