### ISSUE TITLE
libreoffice-style-mint

### ISSUE THREAD

**Issue by volker-raschek** [shimmerproject/libreoffice-style-elementary#4]
Hello, 
it's possible that you can create a libreoffice-style-mint package for Arch Linux?

It's only elementary [available](https://aur.archlinux.org/packages/libreoffice-style-elementary/).

**Comment by ochosi** [comment]
To be honest I neither have the time nor the motivation for another LO icon theme. Maybe I will find the time and energy to add the missing or changed icons in this theme (pull-requests welcome)
